### ISSUE TITLE
Add method to handle updating path

### ISSUE THREAD

**Issue by simpsonjt66** [simpsonjt66/dotfiles#4]
This wonderful explanation comes from [this answer](https://unix.stackexchange.com/a/487889)
### .zshenv
_[Read every time]_

This file is always sourced, so it should set environment variables which need to be **updated frequently**. `PATH` (or its associated counterpart `path`) is a good example because you probably don't want to restart your whole session to make it update. By setting it in that file, reopening a terminal emulator will start a new Zsh instance with the `PATH` value updated.

But be aware that this file is r**ead even when Zsh is launched to run a single command** (with the -c option), even by another tool like make. You should **be very careful to not modify the default behavior of standard commands** because it may break some tools (by setting aliases for example).

### .zprofile
_[Read at login]_

I personally treat that file like .zshenv but for commands and variables which should be set once or which **don't need to be updated frequently:**

- environment variables to configure tools (flags for compilation, data folder location, etc.)
- configuration which execute commands (like `SCONSFLAGS="--jobs=$(( $(nproc) - 1 ))"`) as it may take some time to execute.
If you modify this file, you can apply the configuration updates by running a login shell:

`exec zsh --login`

### .zshrc
_[Read when interactive]_

I put here everything needed only for **interactive usage:**

- prompt,
- command completion,
- command correction,
- command suggestion,
- command highlighting,
- output coloring,
- aliases,
- key bindings,
- commands history management,
- other miscellaneous interactive tools (auto_cd, manydots-magic)...

### .zlogin
_[Read at login]_

This file is like `.zprofile`, but is read after `.zshrc.` You can consider the shell to be fully set up at .zlogin execution time

So, I use it to launch external commands which do not modify shell behaviors (e.g. a login manager).

### .zlogout
_[Read at logout][Within login shell]_

Here, you can clear your terminal or any other resource which was setup at login.

**Comment by simpsonjt66** [comment]
Whoever asked this question on experts exchange, got a plethora of wonderful [replies](https://unix.stackexchange.com/a/71258)
1. Since `.zshenv` is always sourced, it often contains exported variables that should be available to other programs. For example, `$PATH`, `$EDITOR`, and `$PAGER` are often set in .`zshenv`. Also, you can set `$ZDOTDIR` in `.zshenv` to specify an alternative location for the rest of your zsh configuration.

2. .zprofile is basically the same as .zlogin except that it's sourced before .zshrc while .zlogin is sourced instead of directly after it. According to the zsh documentation, ".zprofile is meant as an alternative to .zlogin for ksh fans; the two are not intended to be used together, although this could certainly be done if desired."

3. .zshrc is for interactive shell configuration. You set options for the interactive shell there with the setopt and unsetopt commands. You can also load shell modules, set your history options, change your prompt, set up zle and completion, et cetera. You also set any variables that are only used in the interactive shell (e.g. $LS_COLORS).

4. .zlogin is sourced on the start of a login shell but after .zshrc if the shell is also interactive. This file is often used to start X using startx. Some systems start X on boot, so this file is not always very useful.
.zlogout is sometimes used to clear and reset the terminal. It is called when exiting, not when opening.

**Comment by simpsonjt66** [comment]
This is cut and pasted from @wincent/wincent. I really like the way this handles it, but I think I want to set it in .zshenv.

<script src="https://gist.github.com/simpsonjt66/99dafd0cf623890ea629e5297d3ef26a.js"></script>

**Comment by simpsonjt66** [comment]
This [gist](https://gist.github.com/simpsonjt66/99dafd0cf623890ea629e5297d3ef26a) was plagiarized directly from @wincent.  I like the way he handles this, but want to try it in .zshenv and add in `~/bin`

**Comment by simpsonjt66** [comment]
From this [article](https://medium.com/@rajsek/zsh-bash-startup-files-loading-order-bashrc-zshrc-etc-e30045652f2e) which seems to derive from [this article](https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/).

|                |Interactive login|Interactive non-login|Script|
|-------------|------------------------|------------------------------|--------|
|/etc/zshenv     |    A      |    A      |  A   |
|~/.zshenv       |    B      |    B      |  B   |
|/etc/zprofile   |    C      |           |      |
|~/.zprofile     |    D      |           |      |
|/etc/zshrc      |    E      |    C      |      |
|~/.zshrc        |    F      |    D      |      |
|/etc/zlogin     |    G      |           |      |
|~/.zlogin       |    H      |           |      |
|                 |           |           |      |
|~/.zlogout      |    I      |           |      |
|/etc/zlogout    |    J      |           |      |

**Comment by wincent** [comment]
Nice to see the attention to detail!
